#!/bin/bash
PRODUCTROOT=/Library/WSO2/__TITLE__/__PRODUCT_VERSION__
echo "Chnage Permissions in Product Root..."
cd $PRODUCTROOT
chmod -R ugo+rwx .
[ -d /usr/local/bin ] || mkdir /usr/local/bin

#API Manager 
rm -f /usr/local/bin/__PRODUCT__-__PRODUCT_VERSION__
ln -s $PRODUCTROOT/bin/launcher_wso2server.sh /usr/local/bin/__PRODUCT__-__PRODUCT_VERSION__
